### ISSUE TITLE
yarn create bolt-uxp fails with ENOENT

### ISSUE THREAD

**Issue by jkl3848** [hyperbrew/bolt-uxp#25]
I'm trying to set up a new uxp project and this is my first time using bolt-uxp. I'm following the steps in the README but it keeps failing.

```
node:fs:1028
  binding.rename(
          ^

Error: ENOENT: no such file or directory, rename '/Users/username/Desktop/test_proj/package.vue.json' -> '/Users/username/Desktop/test_proj/package.json'
    at Object.renameSync (node:fs:1028:11)
    at NodeFS.renameSync (/private/var/folders/6v/sfxk5l3s5dl1xfmpbzk9k_k4vg5vp8/T/xfs-d1b2ac46/dlx-70686/.pnp.cjs:3680:24)
    at makeCallSync.Object.assign.code (/private/var/folders/6v/sfxk5l3s5dl1xfmpbzk9k_k4vg5vp8/T/xfs-d1b2ac46/dlx-70686/.pnp.cjs:4270:28)
    at ZipOpenFS.makeCallSync (/private/var/folders/6v/sfxk5l3s5dl1xfmpbzk9k_k4vg5vp8/T/xfs-d1b2ac46/dlx-70686/.pnp.cjs:4621:14)
    at makeCallSync.subPath (/private/var/folders/6v/sfxk5l3s5dl1xfmpbzk9k_k4vg5vp8/T/xfs-d1b2ac46/dlx-70686/.pnp.cjs:4269:19)
    at ZipOpenFS.makeCallSync (/private/var/folders/6v/sfxk5l3s5dl1xfmpbzk9k_k4vg5vp8/T/xfs-d1b2ac46/dlx-70686/.pnp.cjs:4621:14)
    at ZipOpenFS.renameSync (/private/var/folders/6v/sfxk5l3s5dl1xfmpbzk9k_k4vg5vp8/T/xfs-d1b2ac46/dlx-70686/.pnp.cjs:4268:17)
    at VirtualFS.renameSync (/private/var/folders/6v/sfxk5l3s5dl1xfmpbzk9k_k4vg5vp8/T/xfs-d1b2ac46/dlx-70686/.pnp.cjs:3330:24)
    at PosixFS.renameSync (/private/var/folders/6v/sfxk5l3s5dl1xfmpbzk9k_k4vg5vp8/T/xfs-d1b2ac46/dlx-70686/.pnp.cjs:3330:24)
    at NodePathFS.renameSync (/private/var/folders/6v/sfxk5l3s5dl1xfmpbzk9k_k4vg5vp8/T/xfs-d1b2ac46/dlx-70686/.pnp.cjs:3330:24) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'rename',
  path: '/Users/username/Desktop/test_proj/package.vue.json',
  dest: '/Users/username/Desktop/test_proj/package.json'
}
```

I'm setting it up in a blank folder so I'm not sure why its trying to rename a file that does not exist. I even tried making the file but that didn't work.

Here are the build settings I chose:
```
  create-bolt-uxp  
│   by Hyper Brew | https://hyperbrew.co
│
◇  Where do you want to create your project?
│  ./Desktop/test_proj
│
◇  Choose a unique Display Name for your plugin:
│  Bolt UXP
│
◇  Choose a unique ID for your plugin:
│  bolt.uxp.plugin
│
◇  Select framework:
│  Vue
│
◇  Select apps: ( apps marked (Beta) require beta access from Adobe, see readme for more info )
│  Photoshop
│
◇  Do you want to include UXP Hybrid Plugin (C++) files?
│  No
│
◇  Do you want to keep sample code and buttons?
│  Yes
│
◇  Do you want to install dependencies? (recommended)
│  Yes
│
◇  Info ─────────────────────────────────────────────────────╮
│                                                            │
│  Creating Bolt UXP in /Users/username/Desktop/test_proj  │
│                                                            │
├────────────────────────────────────────────────────────────╯
```

**Comment by jkl3848** [comment]
Update: I forked the repo, built and ran locally and had no issues.
